export type InputProps = {
  controlId? : number | any,
  label?: string,
  type? : any,
  placeholder? : string,
  error? : any,
  showError?: string | number,
  inputRef? : any,
  name?: string,
  disabled?: boolean,
  onChange?: Function,
  onBlur?: any,
  buttonLabel?: string,
  isLoading?: boolean,
  isButtonDisabled?: boolean,
  onButtonClick?: Function,
  isRequired?: boolean,
  value?: any,
  isControlled?: boolean,
  iconClass?: string,
  buttonVariant?: string,
  hasButton?: boolean,
  buttonType?: string,
  prependText?: string,
  hintText?: string,
  registeredEvents?: any,
  isPassword?: boolean,
  accept?: boolean,
  autoFocus?: boolean,
  tabindex?: number,
  fieldValues?: string,
  onPaste?: Event,
  id ?: number,
  min ?: any,
  onClick ?: Function,
}
